/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesScreeningsRouteImport } from './routes/services.screenings'
import { Route as ServicesReproductiveHealthRouteImport } from './routes/services.reproductive-health'
import { Route as ServicesMaternityCareRouteImport } from './routes/services.maternity-care'
import { Route as ServicesIvTherapyRouteImport } from './routes/services.iv-therapy'
import { Route as ServicesGeneralHealthcareRouteImport } from './routes/services.general-healthcare'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesScreeningsRoute = ServicesScreeningsRouteImport.update({
  id: '/services/screenings',
  path: '/services/screenings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesReproductiveHealthRoute =
  ServicesReproductiveHealthRouteImport.update({
    id: '/services/reproductive-health',
    path: '/services/reproductive-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMaternityCareRoute = ServicesMaternityCareRouteImport.update({
  id: '/services/maternity-care',
  path: '/services/maternity-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIvTherapyRoute = ServicesIvTherapyRouteImport.update({
  id: '/services/iv-therapy',
  path: '/services/iv-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGeneralHealthcareRoute =
  ServicesGeneralHealthcareRouteImport.update({
    id: '/services/general-healthcare',
    path: '/services/general-healthcare',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/services/general-healthcare': typeof ServicesGeneralHealthcareRoute
  '/services/iv-therapy': typeof ServicesIvTherapyRoute
  '/services/maternity-care': typeof ServicesMaternityCareRoute
  '/services/reproductive-health': typeof ServicesReproductiveHealthRoute
  '/services/screenings': typeof ServicesScreeningsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/services/general-healthcare': typeof ServicesGeneralHealthcareRoute
  '/services/iv-therapy': typeof ServicesIvTherapyRoute
  '/services/maternity-care': typeof ServicesMaternityCareRoute
  '/services/reproductive-health': typeof ServicesReproductiveHealthRoute
  '/services/screenings': typeof ServicesScreeningsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/services/general-healthcare': typeof ServicesGeneralHealthcareRoute
  '/services/iv-therapy': typeof ServicesIvTherapyRoute
  '/services/maternity-care': typeof ServicesMaternityCareRoute
  '/services/reproductive-health': typeof ServicesReproductiveHealthRoute
  '/services/screenings': typeof ServicesScreeningsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/sitemap.xml'
    | '/team'
    | '/services/general-healthcare'
    | '/services/iv-therapy'
    | '/services/maternity-care'
    | '/services/reproductive-health'
    | '/services/screenings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/sitemap.xml'
    | '/team'
    | '/services/general-healthcare'
    | '/services/iv-therapy'
    | '/services/maternity-care'
    | '/services/reproductive-health'
    | '/services/screenings'
  id:
    | '__root__'
    | '/'
    | '/pricing'
    | '/sitemap.xml'
    | '/team'
    | '/services/general-healthcare'
    | '/services/iv-therapy'
    | '/services/maternity-care'
    | '/services/reproductive-health'
    | '/services/screenings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  ServicesGeneralHealthcareRoute: typeof ServicesGeneralHealthcareRoute
  ServicesIvTherapyRoute: typeof ServicesIvTherapyRoute
  ServicesMaternityCareRoute: typeof ServicesMaternityCareRoute
  ServicesReproductiveHealthRoute: typeof ServicesReproductiveHealthRoute
  ServicesScreeningsRoute: typeof ServicesScreeningsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/screenings': {
      id: '/services/screenings'
      path: '/services/screenings'
      fullPath: '/services/screenings'
      preLoaderRoute: typeof ServicesScreeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/reproductive-health': {
      id: '/services/reproductive-health'
      path: '/services/reproductive-health'
      fullPath: '/services/reproductive-health'
      preLoaderRoute: typeof ServicesReproductiveHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/maternity-care': {
      id: '/services/maternity-care'
      path: '/services/maternity-care'
      fullPath: '/services/maternity-care'
      preLoaderRoute: typeof ServicesMaternityCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/iv-therapy': {
      id: '/services/iv-therapy'
      path: '/services/iv-therapy'
      fullPath: '/services/iv-therapy'
      preLoaderRoute: typeof ServicesIvTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/general-healthcare': {
      id: '/services/general-healthcare'
      path: '/services/general-healthcare'
      fullPath: '/services/general-healthcare'
      preLoaderRoute: typeof ServicesGeneralHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  ServicesGeneralHealthcareRoute: ServicesGeneralHealthcareRoute,
  ServicesIvTherapyRoute: ServicesIvTherapyRoute,
  ServicesMaternityCareRoute: ServicesMaternityCareRoute,
  ServicesReproductiveHealthRoute: ServicesReproductiveHealthRoute,
  ServicesScreeningsRoute: ServicesScreeningsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
